linters:
  disable-all: false
  enable:
    - errcheck
    - gocritic
    - staticcheck
    - gosec # 🚀 Activamos gosec para el análisis de seguridad

linters-settings:
  errcheck:
    # Ignora cuando no se comprueban errores en funciones hiper-conocidas o utilidades
    exclude-functions:
      - fmt.Scanln
      - fmt.Printf
      - fmt.Println
      - (*github.com/spf13/viper.Viper).BindEnv
      - github.com/spf13/viper.BindEnv
      - os.WriteFile
      - os.MkdirAll
      - path/filepath.Walk
      - crypto/rand.Read
      - math/rand.Read
      # Métodos de librerías externas o generadas (Cobra, Survey, Gorm)
      - (*github.com/spf13/cobra.Command).Help
      - github.com/AlecAivazis/survey/v2.Ask
      - github.com/AlecAivazis/survey/v2.AskOne
      - (*gorm.io/gorm.DB).AutoMigrate

issues:
  exclude-rules:
    # 1. 🎯 IGNORAR REPOSITORIO COMPLETO DE CLONATOR PARA GOSEC
    # Esto elimina de raíz los falsos positivos de Path Traversal (G304) y bucles Walk (G122)
    - path: cmd/clonator/
      linters:
        - gosec

    # 2. Desactiva gocritic en la carpeta cmd si te molestan los ifElseChain
    - path: cmd/
      linters:
        - gocritic
      text: "ifElseChain"

    # 3. Ignorar por completo el formateo de comentarios molestos en configs
    - path: internal/infrastructure/configuration/
      linters:
        - gocritic
      text: "commentFormatting"

    # 4. Silenciar advertencias de código deprecated (SA1019) en los archivos de test
    - path: _test\.go
      linters:
        - staticcheck
      text: "SA1019"

    # 5. Omitir errcheck en toda la suite de pruebas o utilidades de testing
    - path: internal/testsuite/
      linters:
        - errcheck

    # 6. Silenciar alertas de Path Traversal de gosec en el resto de la capa gAPI si surgen
    - path: internal/infrastructure/gapi/
      linters:
        - gosec
      text: "G703|G304"
