// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: app.proto

package gapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Golden struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Poster        string                 `protobuf:"bytes,6,opt,name=poster,proto3" json:"poster,omitempty"` // ___CUSTOM_FIELDS___
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Golden) Reset() {
	*x = Golden{}
	mi := &file_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Golden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Golden) ProtoMessage() {}

func (x *Golden) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Golden.ProtoReflect.Descriptor instead.
func (*Golden) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{0}
}

func (x *Golden) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Golden) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Golden) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Golden) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Golden) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Golden) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type CreateGoldenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	PosterData    string                 `protobuf:"bytes,3,opt,name=poster_data,json=posterData,proto3" json:"poster_data,omitempty"` // ___CUSTOM_FIELDS___
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoldenRequest) Reset() {
	*x = CreateGoldenRequest{}
	mi := &file_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoldenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoldenRequest) ProtoMessage() {}

func (x *CreateGoldenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoldenRequest.ProtoReflect.Descriptor instead.
func (*CreateGoldenRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGoldenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoldenRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateGoldenRequest) GetPosterData() string {
	if x != nil {
		return x.PosterData
	}
	return ""
}

type CreateGoldenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Poster        string                 `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"` // ___CUSTOM_FIELDS___
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoldenResponse) Reset() {
	*x = CreateGoldenResponse{}
	mi := &file_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoldenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoldenResponse) ProtoMessage() {}

func (x *CreateGoldenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoldenResponse.ProtoReflect.Descriptor instead.
func (*CreateGoldenResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGoldenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateGoldenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoldenResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateGoldenResponse) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type GetGoldenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldenRequest) Reset() {
	*x = GetGoldenRequest{}
	mi := &file_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldenRequest) ProtoMessage() {}

func (x *GetGoldenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldenRequest.ProtoReflect.Descriptor instead.
func (*GetGoldenRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{3}
}

func (x *GetGoldenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGoldenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Poster        string                 `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"` // ___CUSTOM_FIELDS___
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGoldenResponse) Reset() {
	*x = GetGoldenResponse{}
	mi := &file_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGoldenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGoldenResponse) ProtoMessage() {}

func (x *GetGoldenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGoldenResponse.ProtoReflect.Descriptor instead.
func (*GetGoldenResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{4}
}

func (x *GetGoldenResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetGoldenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGoldenResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetGoldenResponse) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

type UpdateGoldenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PosterData    string                 `protobuf:"bytes,4,opt,name=poster_data,json=posterData,proto3" json:"poster_data,omitempty"` // ___CUSTOM_FIELDS___
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoldenRequest) Reset() {
	*x = UpdateGoldenRequest{}
	mi := &file_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoldenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoldenRequest) ProtoMessage() {}

func (x *UpdateGoldenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoldenRequest.ProtoReflect.Descriptor instead.
func (*UpdateGoldenRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGoldenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGoldenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGoldenRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateGoldenRequest) GetPosterData() string {
	if x != nil {
		return x.PosterData
	}
	return ""
}

type UpdateGoldenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       string                 `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGoldenResponse) Reset() {
	*x = UpdateGoldenResponse{}
	mi := &file_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGoldenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGoldenResponse) ProtoMessage() {}

func (x *UpdateGoldenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGoldenResponse.ProtoReflect.Descriptor instead.
func (*UpdateGoldenResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGoldenResponse) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

type DeleteGoldenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoldenRequest) Reset() {
	*x = DeleteGoldenRequest{}
	mi := &file_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoldenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoldenRequest) ProtoMessage() {}

func (x *DeleteGoldenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoldenRequest.ProtoReflect.Descriptor instead.
func (*DeleteGoldenRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGoldenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteGoldenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       string                 `protobuf:"bytes,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoldenResponse) Reset() {
	*x = DeleteGoldenResponse{}
	mi := &file_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoldenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoldenResponse) ProtoMessage() {}

func (x *DeleteGoldenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoldenResponse.ProtoReflect.Descriptor instead.
func (*DeleteGoldenResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGoldenResponse) GetDeleted() string {
	if x != nil {
		return x.Deleted
	}
	return ""
}

type ListGoldensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoldensRequest) Reset() {
	*x = ListGoldensRequest{}
	mi := &file_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoldensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoldensRequest) ProtoMessage() {}

func (x *ListGoldensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoldensRequest.ProtoReflect.Descriptor instead.
func (*ListGoldensRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{9}
}

type ListGoldensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goldens       []*Golden              `protobuf:"bytes,1,rep,name=goldens,proto3" json:"goldens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGoldensResponse) Reset() {
	*x = ListGoldensResponse{}
	mi := &file_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGoldensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGoldensResponse) ProtoMessage() {}

func (x *ListGoldensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGoldensResponse.ProtoReflect.Descriptor instead.
func (*ListGoldensResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{10}
}

func (x *ListGoldensResponse) GetGoldens() []*Golden {
	if x != nil {
		return x.Goldens
	}
	return nil
}

type SearchGoldensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm    string                 `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoldensRequest) Reset() {
	*x = SearchGoldensRequest{}
	mi := &file_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoldensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoldensRequest) ProtoMessage() {}

func (x *SearchGoldensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoldensRequest.ProtoReflect.Descriptor instead.
func (*SearchGoldensRequest) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{11}
}

func (x *SearchGoldensRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *SearchGoldensRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *SearchGoldensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchGoldensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goldens       []*Golden              `protobuf:"bytes,1,rep,name=goldens,proto3" json:"goldens,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGoldensResponse) Reset() {
	*x = SearchGoldensResponse{}
	mi := &file_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGoldensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGoldensResponse) ProtoMessage() {}

func (x *SearchGoldensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGoldensResponse.ProtoReflect.Descriptor instead.
func (*SearchGoldensResponse) Descriptor() ([]byte, []int) {
	return file_app_proto_rawDescGZIP(), []int{12}
}

func (x *SearchGoldensResponse) GetGoldens() []*Golden {
	if x != nil {
		return x.Goldens
	}
	return nil
}

func (x *SearchGoldensResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

var File_app_proto protoreflect.FileDescriptor

const file_app_proto_rawDesc = "" +
	"\n" +
	"\tapp.proto\x12\x06golden\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\x06Golden\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x16\n" +
	"\x06poster\x18\x06 \x01(\tR\x06poster\"d\n" +
	"\x13CreateGoldenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vposter_data\x18\x03 \x01(\tR\n" +
	"posterData\"l\n" +
	"\x14CreateGoldenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06poster\x18\x04 \x01(\tR\x06poster\"\"\n" +
	"\x10GetGoldenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\x11GetGoldenResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06poster\x18\x04 \x01(\tR\x06poster\"t\n" +
	"\x13UpdateGoldenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\vposter_data\x18\x04 \x01(\tR\n" +
	"posterData\"0\n" +
	"\x14UpdateGoldenResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\tR\aupdated\"%\n" +
	"\x13DeleteGoldenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteGoldenResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\tR\adeleted\"\x14\n" +
	"\x12ListGoldensRequest\"?\n" +
	"\x13ListGoldensResponse\x12(\n" +
	"\agoldens\x18\x01 \x03(\v2\x0e.golden.GoldenR\agoldens\"u\n" +
	"\x14SearchGoldensRequest\x12\x1f\n" +
	"\vsearch_term\x18\x01 \x01(\tR\n" +
	"searchTerm\x12\x1f\n" +
	"\vpage_number\x18\x02 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"f\n" +
	"\x15SearchGoldensResponse\x12(\n" +
	"\agoldens\x18\x01 \x03(\v2\x0e.golden.GoldenR\agoldens\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults2\xc8\x03\n" +
	"\rGoldenservice\x12I\n" +
	"\fCreateGolden\x12\x1b.golden.CreateGoldenRequest\x1a\x1c.golden.CreateGoldenResponse\x12@\n" +
	"\tGetGolden\x12\x18.golden.GetGoldenRequest\x1a\x19.golden.GetGoldenResponse\x12I\n" +
	"\fUpdateGolden\x12\x1b.golden.UpdateGoldenRequest\x1a\x1c.golden.UpdateGoldenResponse\x12I\n" +
	"\fDeleteGolden\x12\x1b.golden.DeleteGoldenRequest\x1a\x1c.golden.DeleteGoldenResponse\x12F\n" +
	"\vListGoldens\x12\x1a.golden.ListGoldensRequest\x1a\x1b.golden.ListGoldensResponse\x12L\n" +
	"\rSearchGoldens\x12\x1c.golden.SearchGoldensRequest\x1a\x1d.golden.SearchGoldensResponseB\"Z markitos-it-svc-golden-grpc/gapib\x06proto3"

var (
	file_app_proto_rawDescOnce sync.Once
	file_app_proto_rawDescData []byte
)

func file_app_proto_rawDescGZIP() []byte {
	file_app_proto_rawDescOnce.Do(func() {
		file_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)))
	})
	return file_app_proto_rawDescData
}

var file_app_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_proto_goTypes = []any{
	(*Golden)(nil),                // 0: golden.Golden
	(*CreateGoldenRequest)(nil),   // 1: golden.CreateGoldenRequest
	(*CreateGoldenResponse)(nil),  // 2: golden.CreateGoldenResponse
	(*GetGoldenRequest)(nil),      // 3: golden.GetGoldenRequest
	(*GetGoldenResponse)(nil),     // 4: golden.GetGoldenResponse
	(*UpdateGoldenRequest)(nil),   // 5: golden.UpdateGoldenRequest
	(*UpdateGoldenResponse)(nil),  // 6: golden.UpdateGoldenResponse
	(*DeleteGoldenRequest)(nil),   // 7: golden.DeleteGoldenRequest
	(*DeleteGoldenResponse)(nil),  // 8: golden.DeleteGoldenResponse
	(*ListGoldensRequest)(nil),    // 9: golden.ListGoldensRequest
	(*ListGoldensResponse)(nil),   // 10: golden.ListGoldensResponse
	(*SearchGoldensRequest)(nil),  // 11: golden.SearchGoldensRequest
	(*SearchGoldensResponse)(nil), // 12: golden.SearchGoldensResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_app_proto_depIdxs = []int32{
	13, // 0: golden.Golden.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: golden.Golden.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: golden.ListGoldensResponse.goldens:type_name -> golden.Golden
	0,  // 3: golden.SearchGoldensResponse.goldens:type_name -> golden.Golden
	1,  // 4: golden.Goldenservice.CreateGolden:input_type -> golden.CreateGoldenRequest
	3,  // 5: golden.Goldenservice.GetGolden:input_type -> golden.GetGoldenRequest
	5,  // 6: golden.Goldenservice.UpdateGolden:input_type -> golden.UpdateGoldenRequest
	7,  // 7: golden.Goldenservice.DeleteGolden:input_type -> golden.DeleteGoldenRequest
	9,  // 8: golden.Goldenservice.ListGoldens:input_type -> golden.ListGoldensRequest
	11, // 9: golden.Goldenservice.SearchGoldens:input_type -> golden.SearchGoldensRequest
	2,  // 10: golden.Goldenservice.CreateGolden:output_type -> golden.CreateGoldenResponse
	4,  // 11: golden.Goldenservice.GetGolden:output_type -> golden.GetGoldenResponse
	6,  // 12: golden.Goldenservice.UpdateGolden:output_type -> golden.UpdateGoldenResponse
	8,  // 13: golden.Goldenservice.DeleteGolden:output_type -> golden.DeleteGoldenResponse
	10, // 14: golden.Goldenservice.ListGoldens:output_type -> golden.ListGoldensResponse
	12, // 15: golden.Goldenservice.SearchGoldens:output_type -> golden.SearchGoldensResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_app_proto_init() }
func file_app_proto_init() {
	if File_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_proto_rawDesc), len(file_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_proto_goTypes,
		DependencyIndexes: file_app_proto_depIdxs,
		MessageInfos:      file_app_proto_msgTypes,
	}.Build()
	File_app_proto = out.File
	file_app_proto_goTypes = nil
	file_app_proto_depIdxs = nil
}
