// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: app.proto

package gapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Goldenservice_CreateGolden_FullMethodName  = "/golden.Goldenservice/CreateGolden"
	Goldenservice_GetGolden_FullMethodName     = "/golden.Goldenservice/GetGolden"
	Goldenservice_UpdateGolden_FullMethodName  = "/golden.Goldenservice/UpdateGolden"
	Goldenservice_DeleteGolden_FullMethodName  = "/golden.Goldenservice/DeleteGolden"
	Goldenservice_ListGoldens_FullMethodName   = "/golden.Goldenservice/ListGoldens"
	Goldenservice_SearchGoldens_FullMethodName = "/golden.Goldenservice/SearchGoldens"
)

// GoldenserviceClient is the client API for Goldenservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoldenserviceClient interface {
	CreateGolden(ctx context.Context, in *CreateGoldenRequest, opts ...grpc.CallOption) (*CreateGoldenResponse, error)
	GetGolden(ctx context.Context, in *GetGoldenRequest, opts ...grpc.CallOption) (*GetGoldenResponse, error)
	UpdateGolden(ctx context.Context, in *UpdateGoldenRequest, opts ...grpc.CallOption) (*UpdateGoldenResponse, error)
	DeleteGolden(ctx context.Context, in *DeleteGoldenRequest, opts ...grpc.CallOption) (*DeleteGoldenResponse, error)
	ListGoldens(ctx context.Context, in *ListGoldensRequest, opts ...grpc.CallOption) (*ListGoldensResponse, error)
	SearchGoldens(ctx context.Context, in *SearchGoldensRequest, opts ...grpc.CallOption) (*SearchGoldensResponse, error)
}

type goldenserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoldenserviceClient(cc grpc.ClientConnInterface) GoldenserviceClient {
	return &goldenserviceClient{cc}
}

func (c *goldenserviceClient) CreateGolden(ctx context.Context, in *CreateGoldenRequest, opts ...grpc.CallOption) (*CreateGoldenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGoldenResponse)
	err := c.cc.Invoke(ctx, Goldenservice_CreateGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldenserviceClient) GetGolden(ctx context.Context, in *GetGoldenRequest, opts ...grpc.CallOption) (*GetGoldenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGoldenResponse)
	err := c.cc.Invoke(ctx, Goldenservice_GetGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldenserviceClient) UpdateGolden(ctx context.Context, in *UpdateGoldenRequest, opts ...grpc.CallOption) (*UpdateGoldenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGoldenResponse)
	err := c.cc.Invoke(ctx, Goldenservice_UpdateGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldenserviceClient) DeleteGolden(ctx context.Context, in *DeleteGoldenRequest, opts ...grpc.CallOption) (*DeleteGoldenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGoldenResponse)
	err := c.cc.Invoke(ctx, Goldenservice_DeleteGolden_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldenserviceClient) ListGoldens(ctx context.Context, in *ListGoldensRequest, opts ...grpc.CallOption) (*ListGoldensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGoldensResponse)
	err := c.cc.Invoke(ctx, Goldenservice_ListGoldens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goldenserviceClient) SearchGoldens(ctx context.Context, in *SearchGoldensRequest, opts ...grpc.CallOption) (*SearchGoldensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGoldensResponse)
	err := c.cc.Invoke(ctx, Goldenservice_SearchGoldens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoldenserviceServer is the server API for Goldenservice service.
// All implementations must embed UnimplementedGoldenserviceServer
// for forward compatibility.
type GoldenserviceServer interface {
	CreateGolden(context.Context, *CreateGoldenRequest) (*CreateGoldenResponse, error)
	GetGolden(context.Context, *GetGoldenRequest) (*GetGoldenResponse, error)
	UpdateGolden(context.Context, *UpdateGoldenRequest) (*UpdateGoldenResponse, error)
	DeleteGolden(context.Context, *DeleteGoldenRequest) (*DeleteGoldenResponse, error)
	ListGoldens(context.Context, *ListGoldensRequest) (*ListGoldensResponse, error)
	SearchGoldens(context.Context, *SearchGoldensRequest) (*SearchGoldensResponse, error)
	mustEmbedUnimplementedGoldenserviceServer()
}

// UnimplementedGoldenserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGoldenserviceServer struct{}

func (UnimplementedGoldenserviceServer) CreateGolden(context.Context, *CreateGoldenRequest) (*CreateGoldenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGolden not implemented")
}
func (UnimplementedGoldenserviceServer) GetGolden(context.Context, *GetGoldenRequest) (*GetGoldenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGolden not implemented")
}
func (UnimplementedGoldenserviceServer) UpdateGolden(context.Context, *UpdateGoldenRequest) (*UpdateGoldenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGolden not implemented")
}
func (UnimplementedGoldenserviceServer) DeleteGolden(context.Context, *DeleteGoldenRequest) (*DeleteGoldenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGolden not implemented")
}
func (UnimplementedGoldenserviceServer) ListGoldens(context.Context, *ListGoldensRequest) (*ListGoldensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGoldens not implemented")
}
func (UnimplementedGoldenserviceServer) SearchGoldens(context.Context, *SearchGoldensRequest) (*SearchGoldensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGoldens not implemented")
}
func (UnimplementedGoldenserviceServer) mustEmbedUnimplementedGoldenserviceServer() {}
func (UnimplementedGoldenserviceServer) testEmbeddedByValue()                       {}

// UnsafeGoldenserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoldenserviceServer will
// result in compilation errors.
type UnsafeGoldenserviceServer interface {
	mustEmbedUnimplementedGoldenserviceServer()
}

func RegisterGoldenserviceServer(s grpc.ServiceRegistrar, srv GoldenserviceServer) {
	// If the following call panics, it indicates UnimplementedGoldenserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Goldenservice_ServiceDesc, srv)
}

func _Goldenservice_CreateGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGoldenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).CreateGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_CreateGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).CreateGolden(ctx, req.(*CreateGoldenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goldenservice_GetGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoldenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).GetGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_GetGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).GetGolden(ctx, req.(*GetGoldenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goldenservice_UpdateGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGoldenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).UpdateGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_UpdateGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).UpdateGolden(ctx, req.(*UpdateGoldenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goldenservice_DeleteGolden_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGoldenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).DeleteGolden(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_DeleteGolden_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).DeleteGolden(ctx, req.(*DeleteGoldenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goldenservice_ListGoldens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGoldensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).ListGoldens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_ListGoldens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).ListGoldens(ctx, req.(*ListGoldensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goldenservice_SearchGoldens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGoldensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoldenserviceServer).SearchGoldens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Goldenservice_SearchGoldens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoldenserviceServer).SearchGoldens(ctx, req.(*SearchGoldensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Goldenservice_ServiceDesc is the grpc.ServiceDesc for Goldenservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Goldenservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golden.Goldenservice",
	HandlerType: (*GoldenserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGolden",
			Handler:    _Goldenservice_CreateGolden_Handler,
		},
		{
			MethodName: "GetGolden",
			Handler:    _Goldenservice_GetGolden_Handler,
		},
		{
			MethodName: "UpdateGolden",
			Handler:    _Goldenservice_UpdateGolden_Handler,
		},
		{
			MethodName: "DeleteGolden",
			Handler:    _Goldenservice_DeleteGolden_Handler,
		},
		{
			MethodName: "ListGoldens",
			Handler:    _Goldenservice_ListGoldens_Handler,
		},
		{
			MethodName: "SearchGoldens",
			Handler:    _Goldenservice_SearchGoldens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
